version: '3.4'
services:
  api:
    build: .
    image: promedemoapp:v1
    ports:
      - 8083:80
    depends_on:
      - prometheus
      - grafana
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./data:/var/lib/grafana
    environment:
      - GF_SERVER_ROOT_URL=http://localhost:3000/
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=P@ssword1
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=smtp.gmail.com:587
      - GF_SMTP_USER=shankar.patil784@gmail.com
      - GF_SMTP_FROM_ADDRESS=shankar.patil784@gmail.com
      - GF_SMTP_PASSWORD=ffcztnogbdhyqvyi
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_ALERTING_ERROR_OR_TIMEOUT=keep_state
      - GF_RENDERING_CALLBACK_URL=http://grafana:3000/
      - GF_RENDERING_SERVER_URL=http://renderer:8081/render
    restart: unless-stopped
    depends_on:
      - prometheus 

  renderer:
    image: grafana/grafana-image-renderer:latest
    ports:
      - "8081:8081"
    environment:
      - ENABLE_METRICS=true
      - BROWSER_TZ=Asia/Shanghai
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v2.19.2
    container_name: prometheus
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus/:/etc/prometheus/
    depends_on:
      - cadvisor
  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
  node-exporter:
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command: 
      - '--path.procfs=/host/proc' 
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    ports:
      - 9100:9100
    restart: always
  alertmanager:
    image: prom/alertmanager:v0.21.0
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    environment:
      - GF_SERVER_ROOT_URL=http://localhost:9093/