# alert
rule_files:
  - "alert_rules.yml"
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets: ['alertmanager:9093']


scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  - job_name: api
    metrics_path: /metrics
    static_configs:
      - targets: ['api:80']
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
  - job_name: 'cAdvisor'
    static_configs:
      - targets: ['cadvisor:8080']